services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - media_data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=change_me
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: devdb
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.11-alpine
  celery3:
    container_name: celery3
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=app worker -n emailworker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - redis
  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=app flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery3
volumes:
  db_data:
  media_data:
