# Generated by Django 3.2.25 on 2026-06-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('equipment_type', models.CharField(choices=[('machine', 'Machine'), ('body_weight', 'Body Weight'), ('resistance_band', 'Resistance Band'), ('kettlebell', 'Kettlebell'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_groups', to='tracker.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demo_gif', models.FileField(blank=True, null=True, upload_to='exercise_gifs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('body_part', models.ManyToManyField(blank=True, related_name='exercises', to='tracker.BodyPart')),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='tracker.Equipment')),
                ('muscle_groups', models.ManyToManyField(related_name='exercises', to='tracker.MuscleGroup')),
            ],
        ),
    ]
