# Generated by Django 3.2.25 on 2026-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('cable', 'Cable'), ('body_weight', 'Body Weight'), ('resistance_band', 'Resistance Band'), ('kettlebell', 'Kettlebell'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('other', 'Other'), ('lever_plate_loaded', 'Lever Plate Loaded Machine'), ('lever_selectorized', 'Lever Selectorized Machine'), ('smith_machine', 'Smith Machine'), ('sled', 'Sled')], default='body_weight', max_length=50),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
