# Generated by Django 3.2.25 on 2026-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20260607_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='demo_gif',
        ),
        migrations.AddField(
            model_name='exercise',
            name='execution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='preparation',
            field=models.TextField(blank=True),
        ),
    ]
