# Generated by Django 3.2.25 on 2026-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_program_programworkout_workout_workoutsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsets',
            name='duration_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsets',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsets',
            name='rest_time_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutsets',
            name='set_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsets',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
