# Generated by Django 3.2.25 on 2026-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20260607_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsets',
            name='set_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
