# Generated by Django 3.2.25 on 2026-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
