# Generated by Django 3.2.25 on 2026-04-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loginattempt_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
