# Generated by Django 3.2.25 on 2026-04-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='attempt_count',
        ),
    ]
