# Generated by Django 3.2.25 on 2026-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_loginattempt_attempt_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(null=True)),
                ('locked_until', models.DateTimeField(null=True)),
                ('lockout_reason', models.CharField(choices=[('wrong_password', 'WRONG_PASSWORD'), ('wrong_otp', 'WRONG_OTP')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
