# Generated by Django 3.2.25 on 2026-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accountlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
