# Generated by Django 3.2.25 on 2026-05-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
